spring:
  application:
    name: 피가 되는 연습

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  jpa:
#    show-sql: true
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create
#    database: h2

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    username: sa
#    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: example

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database: mysql

  elasticsearch:
    host: localhost

  config:
    import: classpath:application-secret.yaml

logging:
  level:
    sql: info
    web: info
    org.apache.kafka.clients.NetworkClient: ERROR